article/urls.py
from django.urls import path
from . import views
'''
/article/ => article_list
/article/new => article추가(article_new)
/article/1/detail => 1번 article 상세보기(article_detail)
/article/1/edit => 1번 article 수정(article_edit)
/article/1/delete => 1번 article 삭제(article_delete)
'''
app_name = "article"
urlpatterns = [
    path("", views.article_list, name="list"),
    path("new/", views.article_new, name="new"),
    path("<int:pk>/detail/", views.article_detail, name='detail'),
    path("<int:pk>/edit/", views.article_edit, name='edit'),
    path("<int:pk>/delete/", views.article_delete, name='delete'),
]

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path("", views.list, name="index"), # /blog/ (blog:index)
    path("<int:post_id>/", views.detail, name="detail"), # /blog/2 : int컨버터 이용
]

book/urls.py
from django.urls import path
from . import views
app_name='book'
urlpatterns = [
    path('', views.book_list, name="list"), # /book/
    path('new/', views.book_new, name="new"), # /book/new/
    path('<int:pk>/edit/', views.book_edit, name='edit'),  # /book/1/edit
    path('<int:pk>/delete/', views.book_delete, name='delete') # /book/1/delete
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

# from blog import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", lambda req : redirect("blog:index")),
    path("blog/", include("blog.urls")),
    path("book/", include("book.urls")),
    path("article/", include("article.urls")),
    path("accounts/", include("accounts.urls")),
]
# 장고는 static은 자동 연결해 주나, media는 개발자가 url과 저장경로를 연결
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL, # "/media/~~"
                    document_root = settings.MEDIA_ROOT) # BASE_DIR/_media/ 저장

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!-- Bootstrap 5.3.3 CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  
  <style>
    body {position: relative;}
  </style>
  
  {% load static %}
  <link href="{% static 'img/brand.png' %}" rel="icon">
  <link href="{% static 'css/ex.css' %}" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% include "header.html" %}  
  <div class="p-5 container">
    {% block content %}
    {% endblock %}
  </div>
  {% include "footer.html" with year=2025 %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

myproject/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    /* * * * * footer * * * * * */
    footer{
        margin:5px auto;
        height: 150px;
        overflow: hidden;
    }
    footer div:last-child{
        height:50px; line-height:50px; text-align:center;
        background-color:black;
        color:white;
        position: absolute;
        bottom: 0;
        width:100%;
    }
  </style>
  <title>Title</title>
</head>
<body>
  <footer>
    <div class="copyright">{{ year }}Copyright ⓒ Joeun System Corp. All rights reserved.{{now}}</div>
  </footer>
</body>
</html>

myproject/templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <!-- 브랜드/로고 -->
        <a class="navbar-brand" href="/blog/">
            <img src="{% static 'img/django.png' %}">
        </a>        
        <!-- 모바일용 토글 버튼 -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <!-- 네비게이션 메뉴 -->
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/blog/' %}active{% endif %}" href="/blog/">BLOG</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/article/' %}active{% endif %}" href="{% url 'article:list' %}">Article</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/book/' %}active{% endif %}" href="{% url 'book:list' %}">Book</a>
                </li>                
                <li class="nav-item">
                    <a class="nav-link" href="/admin">Admin</a>
                </li>
            </ul>
            
            <!-- 오른쪽 메뉴 -->
            <ul class="navbar-nav">
                {% if not user.is_authenticated %}
                    {% comment %} 로그인상태가 아닐때 {% endcomment %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">회원 가입</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">로그인</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">{{ user }}님</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">프로필</a>
                    </li>
                    <li class="nav-item">
                        {% comment %} <a class="nav-link" href="{% url 'logout' %}">로그아웃</a> {% endcomment %}
                        <form method="post" action="{% url 'logout' %}?next={{ request.path }}">
                            {% csrf_token %}
                            <button class="nav-link" type="submit">로그아웃</button>
                        </form>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>