blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path("", views.list, name="index"), # /blog/ (blog:index)
    path("<int:post_id>/", views.detail, name="detail"), # /blog/2 : int컨버터 이용
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

# from blog import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", lambda req : redirect("blog:index")),
    path("blog/", include("blog.urls")),
    path("book/", include("book.urls")),
    path("article/", include("article.urls")),
    path("accounts/", include("accounts.urls")),
]
# 장고는 static은 자동 연결해 주나, media는 개발자가 url과 저장경로를 연결
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL, # "/media/~~"
                    document_root = settings.MEDIA_ROOT) # BASE_DIR/_media/ 저장

blog/models.py
from django.db import models
import re
from django.forms import ValidationError
# Create your models here.
REGION_CHOICE = (
  ("Europe","유럽"),
  ("Asia", "아시아"),
  ("Oceania","오세아니아"),
  ("America","아메리카"),
)
def lnglat_validator(value):
  if not re.match(r'(\d+\.?\d*),(\d+\.?\d*)', value):
    raise ValidationError('Invalid LngLat. ex:38, 128')

class Tag(models.Model):
  name = models.CharField(max_length=100, unique=True)
  def __str__(self):
    return self.name

class Post(models.Model): # 테이블명 : blog_post
  # id = models.AutoField(primary_key=True) PK가 없을 경우 자동 생성
  title = models.CharField(verbose_name="제목", 
                          max_length=100,# 최대 길이 반드시 지정 VARCHAR 타입
                          help_text="기사 제목입니다. 100자 내외") 
  content = models.TextField("본문") # 최대길이 제한 없음 CLOB, TEXT타입
  create_at = models.DateField(auto_now_add=True)
  update_at = models.DateTimeField(auto_now=True)
  region = models.CharField(verbose_name="지역",
                            max_length=20, 
                            choices=REGION_CHOICE,
                            default='Asia')
  lnglat = models.CharField(verbose_name="경,위도",
                            max_length=100,
                            blank=True,
                            null=True,
                            help_text="경도, 위도 포맷", # 38.5, 125.8 38,125
                            validators=[lnglat_validator] )
  url = models.URLField(blank=True, null=True)
  tags = models.ManyToManyField(Tag)
  
  def __str__(self):
    return "제목:{}-{}작성 {}최종 수정".format(self.title,
                                      self.create_at,
                                      self.update_at)
  class Meta:
    ordering = ['-update_at'] # 정렬 옵션

class Comment(models.Model): # 테이블명 : blog_comment (Post의 댓글 내용-post:comment=1:N)
  # id = models.AutoField(primary_key=True)
  post = models.ForeignKey(Post, 
                  on_delete=models.CASCADE) # post내용을 delete할 경우 자동 삭제
  author = models.CharField(verbose_name="이름",
                            max_length=20, 
                            null=True, 
                            blank=True)
  message = models.TextField(verbose_name="댓글")
  create_at = models.DateField(auto_now_add=True)
  update_at = models.DateTimeField(auto_now=True)
  def __str__(self):
    return f"{self.post.pk}글의 댓글 - {self.message}(by {self.author})"
  class Meta:
    ordering = ['-create_at', '-update_at']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages # 예외 메세지 담는 역할
from django.http import JsonResponse
from .models import Post
# Create your views here.
def index(request):
  return JsonResponse(
    {'singer':'BTS', 'song':['DNA', 'FAKE LOVE', '피땀눈물']},
    json_dumps_params={'ensure_ascii':False}
  )

def list(request):
  print("request.user :", request.user) # 로그인전:AnonymousUser객체, 로그인후:로그인한 User객체
  post_list = Post.objects.all()
  return render(request, 'blog/index.html', 
                {'post_list': post_list,
                  #'user': request.user
                  })

def detail(request, post_id):
  # post = Post.objects.get(pk=post_id)
  # return render(request, "blog/detail.html", {'post':post})
  # post = get_object_or_404(Post, pk=post_id) # 404 상태 처리
  # return render(request, "blog/detail.html", {'post':post})
  # post = Post.objects.filter(pk=post_id) # 조건에 맞는 데이터를 list로 받음
  # if post:
  #   return render(request, "blog/detail.html", {'post':post[0]})
  # else:
  #   messages.error(request, f"{post_id}번 글이 게시되지 않았습니다")
  #   return redirect("blog:index")
  try:
    post = Post.objects.get(pk=post_id)
    return render(request, "blog/detail.html", {'post':post})
  except Post.DoesNotExist:
    messages.error(request, f"{post_id}번 글이 게시되지 않았습니다")
    return redirect("blog:index")

book/views.py
from django.shortcuts import render, redirect, reverse,  get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import BookModelForm
from .models import Book
# 1. form없이 걍 2. form객체생성후(6장) 3. DjangoGenericView 이용 4. GenericView 상속(7장)

book_list = ListView.as_view(model=Book)
# def book_list(request):
#     return render(request,
#                 'book/book_list.html',
#                 {'book_list':Book.objects.all()})
class BookCreateView(CreateView):
    model = Book
    fields = ['title', 'author', 'publisher', 'sales']
    def form_valid(self, form): # 유효성 검사 성공후 자동 호출
        book = form.save(commit=False)
        book.ip = self.request.META['REMOTE_ADDR']
        book.save()
        return redirect(book) 
book_new = BookCreateView.as_view()

book_new1 = CreateView.as_view(model=Book,
                            fields = ['title', 'author', 'publisher', 'sales'])

def book_new1(request): # GET:template / POST:파라미터변수받아db에 save() ->book:list
    if request.method == 'POST':
        # title = request.POST.get('title')
        # author = request.POST['author']
        # publisher = request.POST['publisher']
        # sales = int(request.POST['sales'])
        # ip    = request.META['REMOTE_ADDR'] # 요청한 client의 ip
        # book = Book(title=title, author=author, publisher=publisher, sales=sales, ip=ip)
        # book.save()
        # return redirect(book) # book.get_absolute_url의 return값 url적용
        form = BookModelForm(request.POST)
        # print('★', form.is_valid()) # 유효성 검증 결과
        # print('유효성 검사 결과 :', form.cleaned_data)
        if form.is_valid(): # 유효성 검사
            #book = Book(**form.cleaned_data)
            #book.ip = request.META['REMOTE_ADDR'] # 요청한 client의 ip
            book = form.save(commit=False)
            book.ip = request.META['REMOTE_ADDR'] # 요청한 client의 ip
            book.save()
            return redirect(book)
    elif request.method == 'GET':
        form = BookModelForm()
    return render(request, 'book/book_form.html', {'form':form})

book_edit = UpdateView.as_view(model=Book,
                            fields = ['title', 'author', 'publisher', 'sales'])

def book_edit1(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookModelForm(request.POST, instance=book)
        if form.is_valid():
            book = form.save() # 수정시 ip 수정X
            # book = form.save(False)
            # book.ip = request.META['REMOTE_ADDR']
            # book.save()
            return redirect(book)
    elif request.method == 'GET':
        form = BookModelForm(instance=book)
    return render(request, 'book/book_form.html', {'form':form})

book_delete = DeleteView.as_view(model=Book,
                        # template_name = "~",
                        success_url = reverse_lazy("book:list"))

def book_delete1(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect(book)
    elif request.method == 'GET':
        return render(request, 
                    'book/book_confirm_delete.html', 
                    {'object':book})

blog/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}{{post.id}}번 post{% endblock %}
{% block content %}
  {% if post %}
    <h2>{{post.id}}.{{post.title}}</h2>
    <p>
      {{post.content}}<br>
      {{post.content | truncatechars:100 }}<br>
      <span>{{post.create_at | date:"Y-m-d"}}</span>
      <span>{{post.update_at | date:"y-m-d A h:i:s"}}</span>
      <span>{{post.update_at | date:"y-m-d H:i:s"}}</span>
    </p>
    <h4>댓글 : {{ post.comment_set.all | length }}개</h4>
    {% for comment in post.comment_set.all %}
      <h6>
        {{comment.message}}
        <span>by {{comment.author}} at {{comment.update_at | date:'y-m-d H:i'}}</span>
      </h6>
    {% endfor %}
    {% comment %} 태그 리스트 출력(태그 없을 경우 없음 출력) {% endcomment %}
    {% for tag in post.tags.all %}  
      #<b>{{tag.name}}</b>
    {% empty %}  
      <h6>등록된 태그가 없습니다</h6>
    {% endfor%}
    <br>
  {% else %}
    <p>No post</p>
  {% endif %}
  <button class="btn btn-primary"
      onclick="location='{% url 'blog:index' %}'">
    목록
  </button>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% block title %}post list{% endblock %}
{% block content %}
<!-- Django 메시지를 Bootstrap Alert로 표시 -->
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'success' %}
      <div class="alert alert-success alert-dismissible fade show">
        ✅ {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
    {% elif message.tags == 'error' %}
      <div class="alert alert-danger alert-dismissible fade show">
        ❌{{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}


{% if post_list %}
    <ul>
    {% for post in post_list %}
      <li>
        {% comment %} <a href="/blog/{{post.id}}/">{{post.id}}.{{post.title}}</a> {% endcomment %}
        <a href="{% url 'blog:detail' post.id %}">{{post.id}}.{{post.title}}</a>
        [<b>{{ post.comment_set.all | length }}개 댓글</b>]
        [{{post.tags.all | length }}개 tag]
        {{post.create_at}} post함 {{post.update_at|date:"y/m/d H:i"}} 최종수정
        {{post.update_at|date:"y/m/d a h:i"}}
      </li>
    {% endfor %}
    </ul>
{% endif %}
{% endblock %}