blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path("", views.list, name="index"), # /blog/ (blog:index)
    path("<int:post_id>/", views.detail, name="detail"), # /blog/2 : int컨버터 이용
]

book/urls.py
from django.urls import path
from . import views
app_name='book'
urlpatterns = [
    path('', views.book_list, name="list"), # /book/
    path('new/', views.book_new, name="new"), # /book/new/
    path('<int:pk>/edit/', views.book_edit, name='edit'),  # /book/1/edit
    path('<int:pk>/delete/', views.book_delete, name='delete') # /book/1/delete
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

# from blog import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", lambda req : redirect("blog:index")),
    path("blog/", include("blog.urls")),
    path("book/", include("book.urls")),
    path("article/", include("article.urls")),
    path("accounts/", include("accounts.urls")),
]
# 장고는 static은 자동 연결해 주나, media는 개발자가 url과 저장경로를 연결
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL, # "/media/~~"
                    document_root = settings.MEDIA_ROOT) # BASE_DIR/_media/ 저장

book/models.py
from django.db import models
from django import forms
from django.core.validators import MinLengthValidator
from django.core.validators import MinValueValidator
from django.core.validators import MaxValueValidator
from django.urls import reverse
# Create your models here.
def min_length_3_validator(value):
    if len(value)<3:
        raise forms.ValidationError('3글자 이상 입력하세요')

class Book(models.Model): # book_book 테이블
    title = models.CharField(verbose_name="책이름", max_length=50)
    author = models.CharField(verbose_name="글쓴이", 
                            max_length=50, 
                            validators=[min_length_3_validator]
                            # validators=[ MinLengthValidator(3)]
                            )
    publisher = models.CharField(verbose_name="출판사",
                                max_length=50,
                                null=True, blank=True)
    sales = models.IntegerField(verbose_name="판매가",
                                default=1000,
                                validators=[MinValueValidator(0),
                                            MaxValueValidator(100000)])
    ip = models.GenericIPAddressField(blank=True, null=True)
    publication_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}:{self.author}저 {self.sales}원 from{self.ip}"
    
    def get_absolute_url(self):
        return reverse("book:list")
    
    class Meta:
        ordering = ['-publication_date']
        unique_together = (('title','author'),) #title과 author가 같으면 저장 불가
    

book/forms.py
from django import forms
from django.core.validators import MinLengthValidator
from django.core.validators import MinValueValidator
from django.core.validators import MaxValueValidator
from .models import Book

def min_length_3_validator(value):
    if len(value)<3:
        raise forms.ValidationError('3글자 이상 입력하세요')

class BookForm(forms.Form): 
    title = forms.CharField(label="책제목")
    author = forms.CharField(label="글쓴이", 
                            validators=[min_length_3_validator]
                            # validators=[ MinLengthValidator(3)]
                            )
    publisher = forms.CharField(label="출판사", required=False)
    sales = forms.IntegerField(label="판매가",
                                initial=1000,
                                validators=[MinValueValidator(0),
                                            MaxValueValidator(100000)])
    def save(self, commit=True):
        book = Book(**self.cleaned_data) # cleaned_data 입력데이터들을 검증 완료 데이터
        if commit:
            book.save()
        return book
    
class BookModelForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'publisher', 'sales']
        # fields = '__all__'

book/views.py
from django.shortcuts import render, redirect, reverse,  get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import BookModelForm
from .models import Book
# 1. form없이 걍 2. form객체생성후(6장) 3. DjangoGenericView 이용 4. GenericView 상속(7장)

book_list = ListView.as_view(model=Book)
# def book_list(request):
#     return render(request,
#                 'book/book_list.html',
#                 {'book_list':Book.objects.all()})
class BookCreateView(CreateView):
    model = Book
    fields = ['title', 'author', 'publisher', 'sales']
    def form_valid(self, form): # 유효성 검사 성공후 자동 호출
        book = form.save(commit=False)
        book.ip = self.request.META['REMOTE_ADDR']
        book.save()
        return redirect(book) 
book_new = BookCreateView.as_view()

book_new1 = CreateView.as_view(model=Book,
                            fields = ['title', 'author', 'publisher', 'sales'])

def book_new1(request): # GET:template / POST:파라미터변수받아db에 save() ->book:list
    if request.method == 'POST':
        # title = request.POST.get('title')
        # author = request.POST['author']
        # publisher = request.POST['publisher']
        # sales = int(request.POST['sales'])
        # ip    = request.META['REMOTE_ADDR'] # 요청한 client의 ip
        # book = Book(title=title, author=author, publisher=publisher, sales=sales, ip=ip)
        # book.save()
        # return redirect(book) # book.get_absolute_url의 return값 url적용
        form = BookModelForm(request.POST)
        # print('★', form.is_valid()) # 유효성 검증 결과
        # print('유효성 검사 결과 :', form.cleaned_data)
        if form.is_valid(): # 유효성 검사
            #book = Book(**form.cleaned_data)
            #book.ip = request.META['REMOTE_ADDR'] # 요청한 client의 ip
            book = form.save(commit=False)
            book.ip = request.META['REMOTE_ADDR'] # 요청한 client의 ip
            book.save()
            return redirect(book)
    elif request.method == 'GET':
        form = BookModelForm()
    return render(request, 'book/book_form.html', {'form':form})

book_edit = UpdateView.as_view(model=Book,
                            fields = ['title', 'author', 'publisher', 'sales'])

def book_edit1(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookModelForm(request.POST, instance=book)
        if form.is_valid():
            book = form.save() # 수정시 ip 수정X
            # book = form.save(False)
            # book.ip = request.META['REMOTE_ADDR']
            # book.save()
            return redirect(book)
    elif request.method == 'GET':
        form = BookModelForm(instance=book)
    return render(request, 'book/book_form.html', {'form':form})

book_delete = DeleteView.as_view(model=Book,
                        # template_name = "~",
                        success_url = reverse_lazy("book:list"))

def book_delete1(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect(book)
    elif request.method == 'GET':
        return render(request, 
                    'book/book_confirm_delete.html', 
                    {'object':book})

book/templates/book/book_confirm_delete.html
{% extends "base.html" %}

{% block title %}책 등록{% endblock %}

{% block content %}
<div class="container-fluid py-5">
  <h1 class="display-5 fw-bold">삭제 확인</h1>
  <p class="col-md-8 fs-4">정말로 "{{ object }}" 항목을 삭제하시겠습니까?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input class="btn btn-primary btn-lg" type="submit" value="삭제">
    <input  class="btn btn-primary btn-lg" type="button" onclick="location='{{object.get_absolute_url}}'" value="취소">
  </form>
</div>
{% endblock %}

book/templates/book/book_form.html
{% extends "base.html" %}

{% block title %}책 등록{% endblock %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table class="table">
      {% comment %} <tr><td>제목</td><td><input type="text" name="title"></td></tr>
      <tr><td>저자</td><td><input type="text" name="author"></td></tr>
      <tr><td>출판사</td><td><input type="text" name="publisher"></td></tr>
      <tr><td>가격</td><td><input type="number" name="sales"></td></tr> {% endcomment %}
      {{form.as_table}}
      <tr>
        <td colspan="2" class="text-center">
          <input type="submit" value="저장">
          <input type="button" value="목록"
          onclick="location='{% url 'book:list'%}'">
        </td>
      </tr>
    </table>
  </form>
{% endblock %}

book/templates/book/book_list.html
{% extends "base.html" %}

{% block title %}Book List{% endblock %}

{% block content %}
  <h2>Book List</h2>
  {% load humanize %} {# intcomma 필터 사용 목적 #}
  {% for book in book_list %}
    <li>
      {{book.id}}.{{book.title}} / {{book.author}}著 / {{book.sales|intcomma }}원 /
      from {{book.ip}}
      {% comment %} <a href="/book/{{book.id}}/edit">[수정]</a>
      <a href="/book/{{book.id}}/delete">[삭제]</a> {% endcomment %}
      <a href="{% url 'book:edit' book.id %}">[수정]</a>
      <a href="{% url 'book:delete' book.id %}">[삭제]</a>
    </li>
  {% empty %}
    <p>도서 목록이 없습니다</p>
  {% endfor %}
  <a href="{% url 'book:new' %}">[BOOK 추가]</a>
{% endblock  %}